wip

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -4,20 +4,52 @@
 #
 # `dot` handles installation, updates, things like that. Run it periodically
 # to make sure you're on the latest and greatest.
-echo "set FISH"
-export FISH=$HOME/dotfiles
-# Set OS X defaults
-echo "set osx defaults"
-$FISH/osx/set-defaults.sh
+
+set -e
+
+parentDirectory="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
+dotfilesDirectory="$(cd "$( dirname "$parentDirectory" )" && pwd -P)"
+
+displayUsageAndExit() {
+	echo "dot -- dotfiles management"
+	echo ""
+	echo "Usage: dot [options]"
+	echo ""
+	echo "Options:"
+	echo "  -e, --edit    Open dotfiles directory for editing"
+	echo "  -h, --help    Show this help message and exit"
+	exit
+}
+
+while test $# -gt 0; do
+	case "$1" in
+		"-h"|"--help")
+			displayUsageAndExit
+			;;
+		"-e"|"--edit")
+			exec "$EDITOR" "$dotfilesDirectory"
+			exit
+			;;
+		*)
+			echo "Invalid option: $1"
+			displayUsageAndExit
+			;;
+	esac
+	shift
+done
+
+export ZSH=$HOME/dotfiles
+
+# Set macOS defaults
+$ZSH/macos/set-defaults.sh
 
 # Install homebrew
-echo "installing homebrew"
-/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+$ZSH/homebrew/install.sh 2>&1
 
 # Upgrade homebrew
-echo "brew update"
+echo "› brew update"
 brew update
 
-# Install homebrew packages
-echo "install homebrew packages"
-$FISH/homebrew/install.sh 2>&1
+# Install software
+echo "› $ZSH/script/install"
+$ZSH/script/install
